name: Android Feature Pipeline

on:
  pull_request:
    branches: ["feature"]
    types: ["opened", "reopened", "synchronize"]

jobs:
  cancel_previous:
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.12.1
        with:
          workflow_id: ${{ github.event.workflow.id }}

  pipeline:
    name: Android Feature Pipeline
    runs-on: macos-latest
    if: (startsWith(github.head_ref, 'documentation/') || startsWith(github.head_ref, 'tests/') || startsWith(github.head_ref, 'infra/')) == false # Skip documentation, tests and infra branches

    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin" # See 'Supported distributions' for available options
          java-version: "17"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: cache gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-core-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-core-

      - name: Add upload and keystore.properties files
        run: |
          pwd
          echo "${{ secrets.UPLOAD }}" | base64 --decode > app/UPLOAD
          echo "${{ secrets.KEYSTORE }}" > keystore.properties
          ls -li

      - name: Check linting
        run: ./gradlew lint

      - name: Check unit tests
        run: ./gradlew test

      - name: Build and Sign
        run: ./gradlew build

      - name: Upload the release apk as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/apk/release/app-release.apk

      # - name: Notify to slack
