name: Android Feature Pipeline

on:
  pull_request:
    branches: ["feature"]
    types: ["opened", "reopened", "synchronize"]

jobs:
  cancel_previous:
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.11.0
        with:
          workflow_id: ${{ github.event.workflow.id }}

  pipeline:
    name: Android Feature Pipeline
    runs-on: macos-latest
    if: (startsWith(github.head_ref, 'documentation/') || startsWith(github.head_ref, 'tests/') || startsWith(github.head_ref, 'infra/')) == false # Skip documentation, tests and infra branches

    steps:
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin" # See 'Supported distributions' for available options
          java-version: "17"

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: cache gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-core-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-core-

      # - name: Check linting
      #   run: ./gradlew lint

      # - name: Check unit tests
      #   run: ./gradlew test

      - name: Build
        run: ./gradlew build

      - name: Sign APK
      run: ./gradlew bundleRelease

      # - name: Notify to slack
